name: Deploy

permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install nix dependencies
        run: nix-env -f "<nixpkgs>" -iA faircamp furnace
      - name: Install webby
        run: cd bin/webby; cargo install --path .
      - name: Build main site
        run: webby
      - name: Upload result
        uses: actions/upload-pages-artifact@v3
        with:
          path: "webby"
      - name: Deploy result
        uses: actions/deploy-pages@v4
